### ISSUE TITLE
Clumps incompatibility

### ISSUE THREAD

**Issue by Desempregago** [RakambdaOrg/OverpoweredMending#65]
### Describe the bug

For some reason, after an item gets repaired, OM skips through the entire hotbar, even if there are other Mending-enchanted items present on it.

[Video Proof](https://streamable.com/r0tmi5) (around 0:38 to be more exact)

### Minecraft version

1.18

### Fabric API version

0.44.0

### Mod version

2.2.6

**Comment by Rakambda** [comment]
[I can't manage to reproduce it](https://youtu.be/qotzB5Kpcpc). Can you try to reproduce it yourself with [this version](https://www.dropbox.com/transfer/AAAAAFxgjExdW62HqWlahqq3gjfSyxr9P9fwWcw3XYB0qWG14koIiVg/edit)?

I added logs. It may create quite larger log files so maybe don't use it for too long.
Though if you manage to reproduce it I'd be interested in the logs it gives when the issue happens.
Logs are `Selected for mending: .....` & `Potential item found for mending: ...`

**Comment by Desempregago** [comment]
Will do. returning after a few minutes of testing

**Comment by Desempregago** [comment]
Uhh... Shouldn't it create log entries when picking experience orbs?

**Comment by Desempregago** [comment]
https://streamable.com/y39yzu

**Comment by Desempregago** [comment]
Mod list
![image](https://user-images.githubusercontent.com/14002834/144942010-07021e90-9ebd-4dc7-bb35-faee23360f0a.png)

PS: I already tested without the XP changing mods, like Linear XP (changes xp level up "costs")

**Comment by Desempregago** [comment]
I think I'll have to do some binary testing. back after a few more minutes.

**Comment by Desempregago** [comment]
Found the culprit: **Clumps**

**Comment by Rakambda** [comment]
I'll try to look into it after work to see if they can be made compatible

**Comment by Rakambda** [comment]
From what I can see Clumps is also [doing some logic](https://github.com/jaredlll08/Clumps/blob/1.18/Common/src/main/java/com/blamejared/clumps/mixin/MixinExperienceOrb.java#L82-L89) when an xp orb is picked up (basically it restores the xp of all the orbs it accumulated).

As the orb is processed and then the [event is cancelled](https://github.com/jaredlll08/Clumps/blob/1.18/Common/src/main/java/com/blamejared/clumps/mixin/MixinExperienceOrb.java#L92) then there's nothing left for OM to do.

I guess there's nothing doable here, mods are simply incompatible.
From my point of view Clumps shouldn't really have to override the "playerTouch" method [as it already redefines the value of the orb](https://github.com/jaredlll08/Clumps/blob/1.18/Common/src/main/java/com/blamejared/clumps/mixin/MixinExperienceOrb.java#L104), but there must be a reason behind it (maybe to have a proper behavior of the normal mending, as if you merged t50 orbs then mending is applied 50 times individually instead of 1 time with the merged value).

**Comment by Rakambda** [comment]
As I don't really see any solutions for now I'll just mention in the description that these mods are incompatible.

**Comment by NolanHewitt** [comment]
Not sure if somethings changed as this issue was made years ago, but I'm using both clumps and this mod and they work together with no issue. Items in my inventory and hotbar that aren't equipped can be repaired with xp.

**Comment by Rakambda** [comment]
Nothing specific was done, but good to know, i'll update the descriptions to mention it 👍
